# Generated by Django 5.1.4 on 2025-01-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0002_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="role_name",
            new_name="name",
        ),
    ]
