# Generated by Django 5.1.4 on 2025-01-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0003_rename_role_name_role_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="name",
            new_name="role_name",
        ),
    ]
