# Generated by Django 5.1.4 on 2025-02-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("franchise", "0004_rename_name_role_role_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="role_name",
            new_name="name",
        ),
    ]
